$schema: https://json-schema.org/draft/2020-12/schema
allOf:
  - $ref: bblocks://ogc.geo.features.featureCollection
  - properties:
      features:
        items:
          $ref: ../forestStandFeature/schema.yaml
