$schema: https://json-schema.org/draft/2020-12/schema
description: My example schema
type: object
properties:
  LT:
    type: string
  LES_OBL:
    type: number
  LO_CAST:
    type: string
  UDRZBA:
    type: number
  ZMENA:
    type: string
  ZADOST:
    type: string
  CHS:
    type: number
  PCHS:
    type: string
  OVER_T:
    type: string
  ROK_MAP:
    type: number
  ID1:
    type: number
  SLT:
    type: string
  PLOCHA:
    type: number
  DS_OPRL:
    type: number
required:
  - LT
